//import liraries
import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  SafeAreaView,
  TouchableOpacity,
  Alert,
  ScrollView,
} from 'react-native';
import CusButton from './Components/CusButton';
import {useState} from 'react';
import {RFPercentage} from 'react-native-responsive-fontsize';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

// create a component
const LogInEmployee = ({navigation}) => {
  const [code, setcode] = useState ('');
  const [password, setpassword] = useState ('');

  const Submit = () => {
    if (code === 'Abc123' && password === '000') {
      navigation.navigate ('Cashier1');
    } else {
      Alert.alert ('Invalid Data');
    }
  };

  return (
    <ScrollView
      style={{
        backgroundColor: 'white',
        flex: 1,
      }}
    >
      <SafeAreaView>
        <View style={styles.container}>
          <View
            style={{
              width: wp ('80%'),
              height: hp ('9%'),
              borderRadius: 5,
              borderColor: '#0000000D',
              alignSelf: 'center',
              justifyContent: 'center',
            }}
          >
            <Text
              style={{
                color: 'darkgreen',
                fontSize: RFPercentage (2.3),
                textAlign: 'center',
                fontFamily: 'PTSerif-Regular',
              }}
            >
              Note: Enter the Code generated by the Admin !
            </Text>
          </View>
          <Text style={styles.text}>Cashier Code:</Text>
          <TextInput
            style={styles.field}
            placeholder="Enter Cashier Code"
            placeholderTextColor={'grey'}
            value={code}
            onChangeText={data => setcode (data)}
            keyboardType="name-phone-pad"
          />
          <Text style={styles.text}>Password:</Text>
          <TextInput
            style={styles.field}
            placeholder="Enter Your Password"
            placeholderTextColor={'grey'}
            value={password}
            onChangeText={data => setpassword (data)}
            secureTextEntry
          />

          <TouchableOpacity
            style={{
              marginTop: hp ('6%'),
            }}
          >
            <CusButton
              text="LogIn"
              backgroundColor={'#1A72DD'}
              color={'white'}
              onPress={() => Submit ()}
            />
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    </ScrollView>
  );
};

// define your styles
const styles = StyleSheet.create ({
  container: {
    marginTop: hp ('5%'),
    flex: 1,
  },

  text: {
    fontSize: RFPercentage (2.7),
    fontFamily: 'PTSerif-Bold',
    color: 'black',
    marginHorizontal: wp ('7%'),
    marginTop: hp ('3%'),
    color: 'black',
  },

  field: {
    borderColor: 'white',
    borderRadius: 15,
    width: wp ('80%'),
    alignSelf: 'center',
    marginTop: hp ('1%'),
    backgroundColor: '#EBEEEE',
    fontFamily: 'PTSerif-Regular',
    color: '#2A3256',
    fontSize: RFPercentage (2.4),
    height: hp ('8%'),
    paddingHorizontal: wp ('7%'),
    elevation: 5,
  },
});

//make this component available to the app
export default LogInEmployee;
